// Generated by CoffeeScript 1.4.0
(function() {
  var create_data_url_scheme, global, main, setup;

  global = this;

  global.app = {
    is_ready: false,
    setup_failed: false,
    config: null
  };

  main = function(config) {
    if (!global.app.setup_failed) {
      global.app.config = new global.config(config.app);
    }
    return global.app.is_ready = true;
  };

  setup = function() {
    return chrome.storage.local.get(["version", "app"], function(config) {
      var default_config, version;
      if (chrome.runtime.lastError != null) {
        global.app.setup_failed = true;
        main(null);
        return;
      }
      version = chrome.runtime.getManifest().version;
      if ((config.version != null) && config.version !== version) {
        return main(null);
      } else if (!(config.version != null)) {
        default_config = {
          version: version,
          app: {
            disabled_all: false,
            rewrite: []
          }
        };
        return chrome.storage.local.set(default_config, function() {
          global.app.setup_failed = chrome.runtime.lastError != null;
          return main(global.app.setup_failed ? null : default_config);
        });
      } else {
        return main(config);
      }
    });
  };

  create_data_url_scheme = function(rewrite) {
    var data;
    data = "data:" + rewrite.mime_header + "/" + rewrite.mime_body;
    if (rewrite.base64) {
      data += ";base64";
    }
    data += "," + rewrite.data;
    return data;
  };

  chrome.runtime.onInstalled.addListener(setup);

  chrome.runtime.onStartup.addListener(setup);

  chrome.webRequest.onBeforeRequest.addListener(function(detail) {
    var rewrite, url_pattern, _i, _len, _ref;
    if (global.app.is_ready && !global.app.setup_failed && !global.app.config.disabled_all()) {
      _ref = global.app.config.get_rewrites();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        rewrite = _ref[_i];
        if (!rewrite.disable) {
          if (rewrite.url_is_regex) {
            url_pattern = new RegExp(rewrite.url);
            if (detail.url.match(url_pattern)) {
              return {
                redirectUrl: create_data_url_scheme(rewrite)
              };
            }
          } else {
            if (detail.url === rewrite.url) {
              return {
                redirectUrl: create_data_url_scheme(rewrite)
              };
            }
          }
        }
      }
      return {
        cancel: false
      };
    } else {
      return {
        cancel: false
      };
    }
  }, {
    urls: ["*://*/*"]
  }, ["blocking"]);

}).call(this);
