// Generated by CoffeeScript 1.4.0
(function() {
  var config, global;

  global = this;

  config = (function() {

    config.prototype._create_id = function() {
      var id;
      id = Math.floor(Math.random() * 1000000);
      while (this._get_rewrite(id) !== null) {
        id = Math.floor(Math.random() * 1000000);
      }
      return id;
    };

    config.prototype._get_rewrite = function(id) {
      var index;
      if ((index = this._get_rewrite_index(id)) !== -1) {
        return this._config.rewrite[index];
      } else {
        return null;
      }
    };

    config.prototype._get_rewrite_index = function(id) {
      var i, rewrite, _i, _len, _ref;
      _ref = this._config.rewrite;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        rewrite = _ref[i];
        if (rewrite.id === id) {
          return i;
        }
      }
      return -1;
    };

    function config(_config) {
      this._config = _config;
    }

    config.prototype.get_rewrite = function(id) {
      return this._get_rewrite(id);
    };

    config.prototype.get_rewrites = function() {
      return this._config.rewrite;
    };

    config.prototype.read_data = function(id, callback) {
      var _this = this;
      return chrome.storage.local.get("data_" + id, function(got) {
        if (chrome.runtime.lastError != null) {
          return callback.call(_this, false, null);
        } else {
          return callback.call(_this, true, got["data_" + id]);
        }
      });
    };

    config.prototype.add = function(title, url, url_is_regex, mime_header, mime_body, base64, data, callback) {
      var id, valid_mime,
        _this = this;
      valid_mime = /^[a-zA-Z\.\-]+$/;
      if (!mime_header.match(valid_mime || !mime_body.match(valid_mime))) {
        callback.call(this, false, null);
      }
      id = this._create_id();
      this._config.rewrite.push({
        id: id,
        title: title,
        url: url,
        url_is_regex: url_is_regex,
        mime_header: mime_header,
        mime_body: mime_body,
        base64: base64,
        data: data,
        disabled: false
      });
      return chrome.storage.local.set({
        app: this._config
      }, function() {
        if (chrome.runtime.lastError != null) {
          _this._config.rewrite.pop();
          return callback.call(_this, false, null);
        } else {
          return callback.call(_this, true, _this._config.rewrite[_this._config.rewrite.length - 1]);
        }
      });
    };

    config.prototype.remove = function(id, callback) {
      var index, removed,
        _this = this;
      if ((index = this._get_rewrite_index(id)) === -1) {
        callback.call(this, false, null);
      }
      removed = this._config.rewrite[index];
      this._config.rewrite.splice(index, 1);
      return chrome.storage.local.set({
        app: this._config
      }, function() {
        if (chrome.runtime.lastError != null) {
          _this._config.rewrite.splice(index, 0, removed);
          return callback.call(_this, false, null);
        } else {
          return callback.call(_this, true, removed);
        }
      });
    };

    config.prototype.override = function(id, title, url, url_is_regex, mime_header, mime_body, base64, data, callback) {
      var backup, index,
        _this = this;
      if ((index = this._get_rewrite_index(parseInt(id))) === -1) {
        callback.call(this, false, null);
      }
      backup = this._config.rewrite[index];
      this._config.rewrite[index] = {
        id: backup.id,
        title: title,
        url: url,
        url_is_regex: url_is_regex,
        mime_header: mime_header,
        mime_body: mime_body,
        base64: base64,
        data: data,
        disabled: backup.disabled
      };
      return chrome.storage.local.set({
        app: this._config
      }, function() {
        if (chrome.runtime.lastError != null) {
          _this._config.rewrite[index] = backup;
          return callback.call(_this, false, null);
        } else {
          return callback.call(_this, true, _this._config.rewrite[index]);
        }
      });
    };

    config.prototype.disabled_all = function() {
      return this._config.disabled_all;
    };

    config.prototype.set_disabled_all = function(boolean, callback) {
      var _this = this;
      this._config.disabled_all = boolean;
      return chrome.storage.local.set({
        app: this._config
      }, function() {
        if (chrome.runtime.lastError != null) {
          return callback.call(_this, false);
        } else {
          return callback.call(_this, true);
        }
      });
    };

    config.prototype.disabled = function(id, boolean, callback) {
      var backup, index,
        _this = this;
      if ((index = this._get_rewrite_index(id)) === null) {
        callback.call(this, false, null);
      }
      backup = this._config.rewrite[index].disabled;
      this._config.rewrite[index].disabled = boolean;
      return chrome.storage.local.set({
        app: this._config
      }, function() {
        if (chrome.runtime.lastError != null) {
          _this._config.rewrite[index].disabled = backup;
          return callback.call(_this, false, _this._config.rewrite[index]);
        } else {
          return callback.call(_this, true, _this._config.rewrite[index]);
        }
      });
    };

    return config;

  })();

  global.config = config;

}).call(this);
